### ISSUE TITLE
 Cache frontiers calls returned data

### ISSUE THREAD

**Issue by talk-code** [talk-code/Hi-Framework#40]
Caching should be activated using annotation on frontier method.
The data should be stored by default on session storage.
```java

@Cacheable()// Cache on session storage for undetermined time 

@Cacheable(permanently=true)//Cache on local storage for undetermined time 

@Cacheable(connectionBind=true)//When connection is lost, the cached data is invalidated 
```

# Caching methods with params 
Caching data from frontier methods that take parameters requires special effort as each invocation
can take its own (different) parameters. Its necessary to define how many invocations will be cached.
The annotation should look like this:
```java
@Cacheable(howMany=5)
```

# Invalidating cache contents
The cache data bound to connection is invalidated once the connection is lost. 
Each frontier method should offer a way of invalidating its cached data. 

```javascript

//Invalidating data cache explicitly
Frontier.method.$invalidateCache();

```

# Updating cached data
The only way to update data on cache for a method is to invoke the method have the that have been invalidated.

**Comment by Romildo-Cumbe** [comment]
This is repeated!
