### ISSUE TITLE
Actions with params not being found if no param is passed from URL

### ISSUE THREAD

**Issue by Romildo-Cumbe** [talk-code/Hi-Framework#69]
`@ApplicationScoped
public class Example extends Controller {

    public void hello(Map params) throws MvcException {
       
//Conent here
    }
}`

When your run the URL: htttp://localhost:8080/MyApp/example/hello

If will return a 404 http error. But it should find the action and set params as null

**Comment by talk-code** [comment]
Bug could not be confirmed. Same procedures were followed but no such issue could be found.
