### ISSUE TITLE
Hi sometimes prints a bunch of variables instead of markup

### ISSUE THREAD

**Issue by Romildo-Cumbe** [talk-code/Hi-Framework#70]
![photo377120621788768185](https://cloud.githubusercontent.com/assets/8167004/17015374/baaf4bf8-4ede-11e6-8743-c9b6f9f56b21.jpg)

In this case, I was using the app on my mobile. I minimized it, and then I went back and it was like this.

Sometimes when you click "back" from your browser.

I didnt yet find a pattern

**Comment by talk-code** [comment]
To fix this, a custom header should be used to detect an AJAX Request

**Comment by Romildo-Cumbe** [comment]
Isn't this closed?

**Comment by talk-code** [comment]
Yah. it is. Closed. Sorry. Had forgot
