### ISSUE TITLE
if no action is mentioned in URL, action named "index" should be called

### ISSUE THREAD

**Issue by Romildo-Cumbe** [talk-code/Hi-Framework#86]
I want URL's like 
https://uezu.org.mz/register-students

The controller is RegisterStudent.class
The action is index

IF no index action found, it should present an error "Expecting a index action" and not "Expecting a action name from the URL"

If no I add a bar "/" it should also work
https://uezu.org.mz/register-students/

It should suport params as any other action

**Comment by talk-code** [comment]
The **index** word should also be hidden on ajax redirects

**Comment by talk-code** [comment]
No slash is supported at the end of the URL

**This works**: https://uezu.org.mz/register-students

**This doesn't work**: https://uezu.org.mz/register-students/
