### ISSUE TITLE
HiList - data listing component

### ISSUE THREAD

**Issue by talk-code** [talk-code/Hi-Framework#9]

**Comment by talk-code** [comment]
**What are the requirements**

- Fetch data from Data Source in a paginated way 

- Templating should be flexible and twekable

- UI Should be extensible

- Search box (on keyup and onenter or custom event) 

- Server-side should allow static data return and should be easy.

**Comment by talk-code** [comment]
```html
<list name="list1" each="row" src="usersPerClass">

           

</list>

**Comment by Romildo-Cumbe** [comment]
`filter-on="enter"  ` should not exist. instead, let the developer decide what event he wants to use  and he will call the "refresh function"

**Comment by Romildo-Cumbe** [comment]
`<header>
                   <input ng-model="list1.search"/>
           </header>

           <content>
                   
                   <item></item>
           </content>

          <footer>
                  
         </footer>` 

Is this mandatory? what items are repeated??

**Comment by Romildo-Cumbe** [comment]
How do I have acces to proprieties like "currentPage", "totalPages"???

**Comment by talk-code** [comment]
``Java

import static  mz.co.hi.web.components.HiList.*;
public class MyFrontier{






}

**Comment by talk-code** [comment]
The only mandatory element is the following:
```html
<content>
<!--There should be only one element here. The one that will be ng-repeated-->
</content>

**Comment by talk-code** [comment]
hiList options:

```html
<list per-page="50" no-header no-footer>

</list>
